
<html>
<head>
   <title>Noise Current</title>
   <link rel="stylesheet" href="button.css">
   
	<style>
		body{
			text-align:center;


			
		}
		.flat-table-1 {
			background: #00008b;
		}
		.flat-table-1 tr:hover {
			background: rgba(0,0,0,0.19);
		}
		h1{
			font-family: Arial, Times, serif;
		}
		table{
			text-align:center;
			margin-left: auto;
			margin-right: auto;
			border:4px solid gray;
			border-collapse:collapse;
			}
		th{
			color:black;
            background-color: white;
			font-size:24px;
			padding:16px;
		}
		
		td{
			text-align:center;
			font-size:22px;
            background-image: url("https://image.freepik.com/free-photo/empty-wood-table-top-nature-green-blurred-background_7182-394.jpg");
			color: black;
			padding: 0px 20px 0px 20px;
		}
		tr{
			transition: background 0.3s, box-shadow 0.3s;
		}
		th,td{
			border-collapse:collapse;
			border:2px groove gray;
			text-shadow: 1px 1px black;
		}
		.hello{
			background-color: lightgray;
			padding: 50px;
  			margin: 20px;
		    
		}
		.css-button{
			margin-left:auto;
			margin-right:auto;
		}
		.button1{
			background-color: aqua;
            border-radius: 100%;
			text-align:center;
			padding-top:2px;
		}
		
		.button1:hover{
			background-color: white;
		}
		.view{
			top:50%;
			padding-top:20px;
			text-align:center;
		}
		.ho{
			padding-top:50px;
			padding-bottom:100px;
		}
		body{
		background-image:url("http://wallpaperheart.com/wp-content/uploads/2018/03/best-background-images-hd-wallpaper.jpg");
		background-position: center;
		background-repeat: no-repeat;
		background-size: cover;
	}
	h2{
		color: red;
	}
	</style>
	
</head>
<h2>--Read the Descriptions before going for the quiz--</h2>
<div class = "hello">In electronics, noise is an unwanted disturbance in an electrical signal. Noise generated by electronic devices varies greatly as it is produced by several different effects. The noise is a summation of unwanted or disturbing energy from natural and sometimes man-made sources.
Current noise is measured by converting the DUT's current noise into a voltage noise, via the RS resistor, which is then amplified and measured by the DSA.
Different types of noise are generated by different devices and different processes.</br>
1) Shot Noise: Shot noise in electronic devices results from unavoidable random statistical fluctuations of the electric current when the charge carriers (such as electrons) traverse a gap. 
The root-mean-square value of the shot noise current in is given by the Schottky formula.

 in = √2IqΔB
where I is the DC current, q is the charge of an electron, and ΔB is the bandwidth in hertz. The Schottky formula assumes independent arrivals.</br></br>
2) Flicker Noise: Flicker noise, also known as 1/f noise, is a signal or process with a frequency spectrum that falls off steadily into the higher frequencies, with a pink spectrum. It occurs in almost all electronic devices and results from a variety of effects.</br></br>
3) Thermal Noise:  Thermal noise is unavoidable at non-zero temperature, and generated by the random thermal motion of charge carriers (usually electrons), inside an electrical conductor, which happens regardless of any applied voltage.</br></br>
4) Burst Noise: Burst noise is a type of electronic noise that occurs in semiconductors and ultra-thin gate oxide films. It is also called random telegraph noise (RTN), popcorn noise, impulse noise, bi-stable noise, or random telegraph signal (RTS) noise.</div>
	


<div class="buttons">
	<a href="quiz page.php">
    <button class="glow-on-hover">Take a quiz</button>
	</a>
</div>
</body>
</html>